name: Notify Docusaurus Repo

on:
  push:
    branches:
      - "autobuild-*" # Remove this after done with testing.
      - develop
      - main
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Docusaurus Update
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.DOCUSAURUS_PAT }}" \
          --data '{"event_type": "sdk_update", "client_payload": { "repo": "'"${{ github.repository }}"'" }}' \
          https://api.github.com/repos/Flyreel/flyreel-sdk-docs/dispatches